update video inference logic
LLaVA-VL/LLaVA-NeXT pull request #205
Opened 2024-09-03 05:32 UTC by ZhangYuanhan-AI

2024-09-03 05:40 UTC, Luodian submitted a review, later dismissed

2024-09-03 07:28 UTC, kcz358 commented on llava/model/llava_arch.py
> +                    import pdb; pdb.set_trace()
Need to delete this line

2024-09-03 07:31 UTC, kcz358 requested changes
There is one debug line needs to be deleted from the code

2024-09-04 02:49 UTC, kcz358 approved these changes

2024-09-17 07:24 UTC, merged